### ISSUE TITLE
HowTo access flask_assets.Bundle.urls from yaml?

### ISSUE THREAD

**Issue by ramschmaerchen** [miracle2k/flask-assets#116]
How do I access Bundle.urls when using from_yaml?

The following works but I can not access `urls` when registered via a yaml file.

### registered in code works:
```python
test = Bundle('scss/test.scss', filters="pyscss", output='compiled/test.css')
assets.register("test", test)
print(test.urls())
```
```bash
# Output
/static/compiled/test.css?68b329da
```

### registered in yaml does not:
```yaml
test:
    filters: pyscss
    output: compiled/test.css
    contents:
        - scss/test.scss
```
```python
assets.from_yaml("static/assets.yaml")
print(test.urls())
```
```bash
# Output
NameError: name 'test' is not defined
```
